const SUPABASE_URL = 'https://xokmikmamamkurfyxunz.supabase.co';
const SUPABASE_KEY = 'sb_publishable_j1N3Rq91kq2paXKR_hBU1w_OC0rRSRV';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = (id) => document.getElementById(id);
let companies = [], filter = 'today', selectedOutcome = 'no_answer';
const OUTCOMES = {no_answer:'Не ответили',not_interested:'Неинтересно',whatsapp_sent:'Отправил WhatsApp',callback:'Нужен перезвон',interested:'Есть интерес',custom:'Свой результат'};
const localDate = (date) => { const d = date ? new Date(date) : new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16); };
const today = () => new Date().toISOString().slice(0,10);
function formatDate(v){if(!v)return 'без даты';return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));}
function whatsappUrl(phone){return `https://wa.me/${(phone||'').replace(/\D/g,'')}`;}
function setAuthMessage(msg=''){ $('auth-message').textContent=msg; }
async function showApp(){ $('auth-view').hidden=true;$('app-view').hidden=false;$('today-label').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());await loadCompanies(); }
async function loadCompanies(){ const {data,error}=await supabase.from('companies').select('*').order('next_action_at',{ascending:true,nullsFirst:false});if(error){alert(error.message);return;}companies=data||[];render(); }
function filtered(){ const start=today();if(filter==='all')return companies;if(filter==='overdue')return companies.filter(c=>c.next_action_at&&c.next_action_at.slice(0,10)<start);return companies.filter(c=>c.next_action_at&&c.next_action_at.slice(0,10)===start); }
function render(){ const items=filtered();$('today-count').textContent=items.length;$('task-list').innerHTML=items.map(c=>{const overdue=c.next_action_at&&c.next_action_at.slice(0,10)<today();return `<article class="task-card ${overdue?'overdue':''}"><div><h2>${escapeHtml(c.company_name)}</h2><div class="meta"><span class="badge">${c.language}</span>${c.contact_name?`<span>${escapeHtml(c.contact_name)}</span>`:''}<span>${overdue?'Просрочено: ':''}${formatDate(c.next_action_at)}</span></div></div><div class="card-actions"><a class="call" href="tel:${encodeURIComponent(c.phone||'')}"><button class="call">Позвонить</button></a><a target="_blank" rel="noopener" href="${whatsappUrl(c.whatsapp||c.phone)}"><button class="wa">WhatsApp</button></a><button class="more" data-edit="${c.id}">⋯</button></div></article>`;}).join('');$('empty-state').hidden=items.length!==0;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openCompany(companies.find(c=>c.id===b.dataset.edit))); }
function escapeHtml(text=''){return text.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function openCompany(c=null){$('company-form').reset();$('company-id').value=c?.id||'';$('dialog-title').textContent=c?'Компания':'Новая компания';$('company-name').value=c?.company_name||'';$('contact-name').value=c?.contact_name||'';$('phone').value=c?.phone||'';$('language').value=c?.language||'EN';$('next-action').value=c?.next_action_at?localDate(c.next_action_at):localDate();$('notes').value=c?.notes||'';$('delete-company').hidden=!c;$('company-dialog').showModal();}
function openOutcome(c){ $('outcome-company').textContent=c.company_name;selectedOutcome='no_answer';$('outcome-note').value='';$('outcome-next').value=localDate();$('outcome-options').innerHTML=Object.entries(OUTCOMES).map(([k,v])=>`<button type="button" class="outcome ${k===selectedOutcome?'selected':''}" data-outcome="${k}">${v}</button>`).join('');document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>{selectedOutcome=b.dataset.outcome;document.querySelectorAll('[data-outcome]').forEach(x=>x.classList.toggle('selected',x===b));});$('outcome-dialog').dataset.companyId=c.id;$('outcome-dialog').showModal(); }
$('auth-form').onsubmit=async(e)=>{e.preventDefault();setAuthMessage();$('auth-submit').disabled=true;const {error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('auth-submit').disabled=false;if(error)setAuthMessage(error.message);else showApp();};
$('signup-button').onclick=async()=>{setAuthMessage();const {error}=await supabase.auth.signUp({email:$('email').value,password:$('password').value});setAuthMessage(error?'Ошибка: '+error.message:'Проверь почту и подтверди аккаунт. Затем войди.');};
$('signout').onclick=async()=>{await supabase.auth.signOut();location.reload();};
$('new-company').onclick=() => openCompany();$('empty-add').onclick=()=>openCompany();$('cancel-dialog').onclick=()=>$('company-dialog').close();$('cancel-outcome').onclick=()=>$('outcome-dialog').close();
$('company-form').onsubmit=async(e)=>{e.preventDefault();const id=$('company-id').value;const row={company_name:$('company-name').value.trim(),contact_name:$('contact-name').value.trim()||null,phone:$('phone').value.trim()||null,whatsapp:$('phone').value.trim()||null,language:$('language').value,next_action_at:$('next-action').value?new Date($('next-action').value).toISOString():null,notes:$('notes').value.trim()||null,updated_at:new Date().toISOString()};const q=id?supabase.from('companies').update(row).eq('id',id):supabase.from('companies').insert(row);const {error}=await q;if(error)alert(error.message);else{$('company-dialog').close();await loadCompanies();}};
$('delete-company').onclick=async()=>{if(!confirm('Удалить компанию и её историю звонков?'))return;const {error}=await supabase.from('companies').delete().eq('id',$('company-id').value);if(error)alert(error.message);else{$('company-dialog').close();loadCompanies();}};
$('outcome-form').onsubmit=async(e)=>{e.preventDefault();const id=$('outcome-dialog').dataset.companyId;const next=$('outcome-next').value?new Date($('outcome-next').value).toISOString():null;const note=$('outcome-note').value.trim()||null;const {error}=await supabase.from('call_logs').insert({company_id:id,outcome:selectedOutcome,note,next_action_at:next});if(error){alert(error.message);return;}const upd=await supabase.from('companies').update({status:selectedOutcome,custom_status:selectedOutcome==='custom'?note:null,last_contacted_at:new Date().toISOString(),next_action_at:next,updated_at:new Date().toISOString()}).eq('id',id);if(upd.error){alert(upd.error.message);return;}$('outcome-dialog').close();await loadCompanies();};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render();});
document.addEventListener('click',e=>{const c=e.target.closest('.call');if(c?.tagName==='BUTTON'){const card=e.target.closest('.task-card');const company=companies.find(x=>x.id===card.querySelector('[data-edit]')?.dataset.edit);if(company)setTimeout(()=>openOutcome(company),250);}});
supabase.auth.getSession().then(({data:{session}})=>{if(session)showApp();});
